export enum ActionType {
  RESET = 'COMMON/RESET',
  INIT_APP = 'COMMON/INIT_APP',
  INIT_APP_SUCCESS = 'COMMON/INIT_APP_SUCCESS',
  ERROR = 'COMMON/ERROR',
  INFO = 'COMMON/INFO',
  SUCCESS = 'COMMON/SUCCESS',
  DISMISS_MESSAGE = 'COMMON/DISMISS_MESSAGE',
  SET_CONFIG = 'COMMON/SET_CONFIG',
}
