export enum ActionType {
  RESET = 'ORDER/RESET',
  SET_PAY_ORDER = 'ORDER/SET_PAY_ORDER',
  LOAD_ORDERS = 'ORDER/LOAD_ORDERS',
  LOAD_ORDERS_SUCCESS = 'ORDER/LOAD_ORDERS_SUCCESS',
  LOAD_ORDERS_FAIL = 'ORDER/LOAD_ORDERS_FAIL',
}
