export enum ActionType {
  INIT = 'USER/INIT',
  INIT_SUCCESS = 'USER/INIT_SUCCESS',
  LOGOUT = 'USER/LOGOUT',
  SET_USER_INFO = 'USER/SET_USER_INFO',
  GET_WALLET_INFO = 'USER/GET_WALLET_INFO',
  GET_WALLET_INFO_SUCCESS = 'USER/GET_WALLET_INFO_SUCCESS',
  GET_COUPON_LIST = 'USER/GET_COUPON_LIST',
  GET_COUPON_LIST_SUCCESS = 'USER/GET_COUPON_LIST_SUCCESS',
  GET_MINE_DETAIL = 'USER/GET_MINE_DETAIL',
  GET_MINE_DETAIL_SUCCESS = 'USER/GET_MINE_DETAIL_SUCCESS',
}
