export enum ActionType {
  RESET = 'WORK/RESET',
  CHANGE_TAB = 'WORK/CHANGE_TAB',
  SET_VIDEO_INFO = 'WORK/SET_VIDEO_INFO',
  SET_WORK_SPU = 'WORK/SET_WORK_SPU',
  SET_PUBLISH_CONFIG = 'WORK/SET_PUBLISH_CONFIG',
}
